const fs = require('fs');
const f = 'extension/dist/content.js';
let s = fs.readFileSync(f, 'utf8');

const startMarker = '  function selectPairViaAssetPicker(asset) {';
const endMarker = '  /**\n   * Verify a pair switch actually took effect.';
const start = s.indexOf(startMarker);
const end = s.indexOf(endMarker);
if (start === -1 || end === -1 || end <= start) throw new Error('picker block not found');

const newPicker = [
'  /**',
'   * Switch the chart via Quotex\'s own asset picker modal.',
'   * Strategy: after opening the modal, POLL for a clickable row naming the target',
'   * pair — the full unfiltered list usually already shows every open pair, so no',
'   * typing is needed at all. Only when the row is not on screen do we type into the',
'   * search box (React-safe native setter), then poll again. On total failure the',
'   * modal is closed (Escape / X) so it can never stay stuck over the chart.',
'   */',
'  function selectPairViaAssetPicker(asset) {',
'    const clean = String(asset).toUpperCase().replace(/\s*\(OTC\)/i, "").trim();',
'    const opener = detectFromDealForm(window.innerWidth);',
'    if (!opener || !opener.element) return Promise.resolve(false);',
'    dispatchFullClick(opener.element);',
'',
'    const findRow = () => {',
'      const rows = document.querySelectorAll("div, span, button, li");',
'      let best = null;',
'      for (const el of rows) {',
'        if (el.closest("#otc-swarm-queen-hud")) continue;',
'        if (el.children.length > 4) continue;',
'        const r = el.getBoundingClientRect();',
'        if (r.width < 40 || r.width > 600 || r.height < 18 || r.height > 90) continue;',
'        const txt = (el.textContent || "").toUpperCase().replace(/\s+/g, " ").trim();',
'        if (!txt.includes(clean)) continue;',
'        if (txt.length > clean.length + 60) continue; // never a whole section',
'        const area = r.width * r.height;',
'        if (!best || area < best.area) best = { el: el, area: area };',
'      }',
'      return best;',
'    };',
'',
'    const typeSearch = () => {',
'      try {',
'        const inputs = Array.from(document.querySelectorAll("input[type=\'text\'], input[type=\'search\'], input:not([type])"))',
'          .filter((inp) => {',
'            const r = inp.getBoundingClientRect();',
'            return r.width > 60 && r.height > 16 && inp.offsetParent !== null;',
'          });',
'        const searchInput = inputs[inputs.length - 1];',
'        if (!searchInput) return;',
'        searchInput.focus();',
'        const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value").set;',
'        if (setter) setter.call(searchInput, clean);',
'        else searchInput.value = clean;',
'        searchInput.dispatchEvent(new Event("input", { bubbles: true }));',
'        searchInput.dispatchEvent(new Event("change", { bubbles: true }));',
'      } catch (e) {}',
'    };',
'',
'    const closePairModal = () => {',
'      try {',
'        document.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", keyCode: 27, which: 27, bubbles: true }));',
'        const closeEl = Array.from(document.querySelectorAll("[class*=\'close\'], button"))',
'          .find((el) => {',
'            if (el.closest("#otc-swarm-queen-hud")) return false;',
'            const t = (el.textContent || "").trim();',
'            const r = el.getBoundingClientRect();',
'            return (t === "\u00d7" || t === "X" || t === "\u2715" || /close/i.test(String(el.className))) && r.width > 0 && r.width < 80;',
'          });',
'        if (closeEl) dispatchFullClick(closeEl);',
'      } catch (e) {}',
'    };',
'',
'    return new Promise((resolve) => {',
'      let tries = 0;',
'      const poll = () => {',
'        tries++;',
'        const row = findRow();',
'        if (row) {',
'          dispatchFullClick(row.el);',
'          // Give the click a beat, then try once more — some builds need a second',
'          // click on the row before the pair actually switches.',
'          setTimeout(() => { try { const again = findRow(); if (again) dispatchFullClick(again.el); } catch (e) {} }, 150);',
'          setTimeout(() => resolve(true), 300);',
'          return;',
'        }',
'        if (tries === 2 || tries === 4 || tries === 6) typeSearch();',
'        if (tries >= 12) {',
'          closePairModal();',
'          resolve(false);',
'          return;',
'        }',
'        setTimeout(poll, 250);',
'      };',
'      setTimeout(poll, 500);',
'    });',
'  }',
'',
''].join('\n');
s = s.slice(0, start) + newPicker + s.slice(end);
fs.writeFileSync(f, s);
console.log('picker rewritten');
